title: "The Curious Outsider"
description: "An early stage knowledge base project."
url: "https://thumbliner.com"
baseurl: "thumbliner"   # keep empty since you'll serve from the root

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  
search_enabled: true
color_scheme: "light"   # auto = follows user’s light/dark preference

logo: "/assets/logo.png"
favicon_ico: "/favicon.ico"
